### ISSUE TITLE
音频播放时报错

### ISSUE THREAD

**Issue by fengdi926** [lizixian18/NiceMusic#9]
android.os.DeadObjectException
2019-01-17 17:59:42.186 21834-21834/com.moocxuetang W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2019-01-17 17:59:42.186 21834-21834/com.moocxuetang W/System.err:     at android.os.BinderProxy.transact(Binder.java:767)
2019-01-17 17:59:42.186 21834-21834/com.moocxuetang W/System.err:     at com.lzx.musiclibrary.aidl.source.IPlayControl$Stub$Proxy.resumeMusic(IPlayControl.java:581)
2019-01-17 17:59:42.186 21834-21834/com.moocxuetang W/System.err:     at com.lzx.musiclibrary.manager.MusicManager.resumeMusic(MusicManager.java:409)
2019-01-17 17:59:42.186 21834-21834/com.moocxuetang W/System.err:     at com.moocxuetang.window.SignMembersPop$3$1.run(SignMembersPop.java:233)
2019-01-17 17:59:42.186 21834-21834/com.moocxuetang W/System.err:     at android.app.Activity.runOnUiThread(Activity.java:6507)
2019-01-17 17:59:42.186 21834-21834/com.moocxuetang W/System.err:     at com.moocxuetang.window.SignMembersPop$3.onClick(SignMembersPop.java:227)

大神，这该怎么解决呢？

**Comment by lizixian18** [comment]
要不你用新版本试试？不知道更换其他对你来说方不方便。。
